version: "2.4"
services:
  openwb:
    build: 
      context: .
      dockerfile: Dockerfile
    init: true
    container_name: openwb
    ports:
      - "80:80"
      - "9001:9001"
      - "1883:1883"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: "Europe/Berlin"
      WEB_PORT: 80
    volumes:
      - type: bind
        source: ./openwb.conf
        target: /var/www/html/openWB/openwb.conf
      - type: bind
        source: ./logdata
        target: /var/www/html/openWB/web/logging/data
      - type: bind
        source: ./mosquitto
        target: /var/lib/mosquitto
      - type: bind 
        source: ./
        target: /var/www/html/openWB
